version: 2
orbs:
  cypress: cypress-io/cypress@1
jobs:
  build:
    docker:
      - image: circleci/node:14-browsers

    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - run: yarn format:check
      - run: yarn lint
      - run: yarn lint:language
