version: 2
orbs:
  cypress: cypress-io/cypress@1
jobs:
  build:
    docker:
      - image: circleci/node:14-browsers

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: 'yarn install'
      - run:
          name: Format Check
          command: 'yarn format:check'
      - run:
          name: Lint
          command: 'yarn lint'
      - run:
          name: Lint languages
          command: 'yarn lint:languages'
